[workspace]
members = [
	"examples/async-sqlite",
	"examples/cpu-count",
	"examples/gzip-stream",
	"examples/hello-world",
	"examples/logging",
	"examples/tokio-fetch",
]

[profile.release]
lto = true
